// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPsCALlIbu-3Jn_ps_5NOxU7yNMI8WzIg',
    appId: '1:987907829931:web:8de1a2695b34f5ee8307ee',
    messagingSenderId: '987907829931',
    projectId: 'scholarship-573db',
    authDomain: 'scholarship-573db.firebaseapp.com',
    storageBucket: 'scholarship-573db.firebasestorage.app',
    measurementId: 'G-S58P03DWS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlKWyhKkMdv-LtyVsmLDt5CQImhs8vZHM',
    appId: '1:987907829931:android:968e4288e71e54858307ee',
    messagingSenderId: '987907829931',
    projectId: 'scholarship-573db',
    storageBucket: 'scholarship-573db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG0yq2gIbBb9QvV-vgP-mQ0OlkK2n1_Gg',
    appId: '1:987907829931:ios:6c710c265b65ba0b8307ee',
    messagingSenderId: '987907829931',
    projectId: 'scholarship-573db',
    storageBucket: 'scholarship-573db.firebasestorage.app',
    iosBundleId: 'com.example.scholarship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG0yq2gIbBb9QvV-vgP-mQ0OlkK2n1_Gg',
    appId: '1:987907829931:ios:6c710c265b65ba0b8307ee',
    messagingSenderId: '987907829931',
    projectId: 'scholarship-573db',
    storageBucket: 'scholarship-573db.firebasestorage.app',
    iosBundleId: 'com.example.scholarship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPsCALlIbu-3Jn_ps_5NOxU7yNMI8WzIg',
    appId: '1:987907829931:web:14ea3c42ca0b653b8307ee',
    messagingSenderId: '987907829931',
    projectId: 'scholarship-573db',
    authDomain: 'scholarship-573db.firebaseapp.com',
    storageBucket: 'scholarship-573db.firebasestorage.app',
    measurementId: 'G-TN9KZJG32W',
  );
<<<<<<< HEAD
}
=======
}
>>>>>>> dev_sushmidha
